sonar.projectKey=rgkim-hsu_Smart-Farm-moxer
sonar.organization=rgkim-hsu
sonar.projectName=Smart Farm Algeria (FastAPI + React)
sonar.projectVersion=1.0
sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc,**/alembic/**,**/venv/**,**/.venv/**
sonar.python.version=3.10,3.11
